name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Run Linter
        run: |
          if [ -f "eslint.config.js" ] || [ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ]; then
            npm run lint || true
          else
            echo "No ESLint config found, skipping lint step."
          fi

      - name: Run Tests
        run: |
          if [ -d "__tests__" ] || [ -d "tests" ]; then
            npm test || true
          else
            echo "No test directory found, skipping tests."
          fi

      - name: Upload Artifacts (build/test results)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-results
          path: |
            build/
            test-results/
            coverage/

