name: Custom Workflow - Release Notes Generator

on:
  push:
    tags:
      - 'v*'         
  workflow_dispatch:  

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Release Notes
        run: |
          mkdir -p release_notes
          echo "# Release Notes" > release_notes/notes.md
          echo "Generated on $(date)" >> release_notes/notes.md
          echo "" >> release_notes/notes.md
          echo "## Recent Commits" >> release_notes/notes.md
          git log -5 --pretty=format:"- %s (%an)" >> release_notes/notes.md

      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes/

